// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface CouponResponse {
  code:    string;
  message: string;
  content: Coupon;
}

export interface Coupon {
  couponId:       string;
  subTotal:       number;
  discount:       number;
  costOfShipping: number;
  total:          number;
}

