// Generated by https://quicktype.io

export interface ResponseEvents {
  code:    string;
  message: string;
  content: Events[];
}

export interface Events {
  id:     number;
  name:   string;
  status: string;
}
