// Generated by https://quicktype.io

export interface ShipmentsResponse {
  code: string;
  message: string;
  content: Shipments[];
}

export interface Shipments {
  shipmentId: number;
  guideNumber: string;
  shipmentStatus: ShipmentsStatus;
  createdAt: string;
  sendAt: string;
  deliveredAt: string;
  transportCompany: string;
  transportCompanyTraceUrl: string;
  warehouse: string;
  subTotal: number;
  discount: number;
  costOfShipping: number;
  total: number;
  detail: Product[];
}

export enum ShipmentsStatus {
  Send = 'SEND',
  Returned = 'RETURNED',
}

export interface Product {
  productId: number;
  quantity: number;
  previousPrice: number;
  price: number;
  discount: number;
  costOfShipping: number;
  productName: string;
  productDescription: string;
  productDetail: ProductDetail[];
  productImages: ProductImage[];
}

export interface ProductDetail {
  label: string;
  value: string;
}

export interface ProductImage {
  key: string;
  principal: boolean;
}
